
services:
  
  # Product Catalog API Service
  product-catalog-api:
    image: product-catalog-api:latest
    container_name: product-catalog-api
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"  # Expose API service on port 5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=sql-server-db;Database=ProductCatalogDb;User=sa;Password=Password;
      - JWT__SecretKey=your_secret_jwt_key
      - Redis__ConnectionString=redis-cache:6379
      - Serilog__WriteTo__0__Args__nodeUris=http://opensearch:9200
    depends_on:
    #  - sql-server-db
     # - redis-cache
      - opensearch
    networks:
      - product-catalog-network

  # SQL Server Database
  # sql-server-db:
    # image: mcr.microsoft.com/mssql/server:2019-latest
    # container_name: sql-server-db
    # environment:
      # SA_PASSWORD: "password10"
      # ACCEPT_EULA: "Y"
    # ports:
      # - "1433:1433"  # Expose SQL Server on port 1433
    # volumes:
      # - sql-server-data:/var/opt/mssql
    # networks:
      # - product-catalog-network

  # Redis Cache Service
  # redis-cache:
    # image: redis:latest
    # container_name: redis-cache
    # ports:
      # - "6379:6379"  # Expose Redis on port 6379
    # networks:
      # - product-catalog-network

  # OpenSearch Service
  opensearch:
    image: opensearchproject/opensearch:2.8.0
    container_name: opensearch
    environment:
      - discovery.type=single-node
      - "DISABLE_INSTALL_DEMO_CONFIG=true"
      - "DISABLE_SECURITY_PLUGIN=true"
    ports:
      - "9200:9200"  # OpenSearch HTTP port
      - "9600:9600"  # OpenSearch metrics port
    networks:
      - product-catalog-network

  # Kibana for OpenSearch
  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:2.8.0
    container_name: opensearch-dashboards
    ports:
      - "5601:5601"  # Kibana Dashboard on port 5601
    environment:
      - OPENSEARCH_HOSTS=http://opensearch:9200
      - "DISABLE_SECURITY_DASHBOARDS_PLUGIN=true"
    networks:
      - product-catalog-network

networks:
  product-catalog-network:
    driver: bridge

volumes:
  sql-server-data:
    driver: local
